### ISSUE TITLE
Couldn't parse IP from header

### ISSUE THREAD

**Issue by petrkr** [hoytech/strfry#125]
Strfry can not parse IPv4 in IPv6 format.

Example
 x-real-ip: ffff:11.22.33.44

**Comment by hoytech** [comment]
Hi! As I mentioned in #50 , the proper formatting is `::ffff:11.22.33.44` (you need leading `::` characters).

However, I looked into it and noticed that uWebsockets is stripping out leading `:` characters. I consider this a bug, and I may fix it in my fork some day. For now I added a hack to strfry so that it can parse these addresses. If you upgrade to release 1.0.2 it should be fixed for you. Thanks for the report!

**Comment by petrkr** [comment]
Oh sorry, i did not remember I already fill it year ago and probably used bad search..

Maybe It can be fixed by haproxy configuration, where I'lll open separated ipv4 socket, so it will notbuse ffff anotation, but regular IP.

I did not thought it is different, but 4d ago I heard that at one presentation at Linux days, when they had talk about IPv6 networks and used haproxy as ingress too

**Comment by hoytech** [comment]
The way I wrote it, `ffff:11.22.33.44` (no leading `::`) will actually work as expected now in version 1.0.2, even though that is not technically correct. :)

**Comment by petrkr** [comment]
Also using of 
```
   bind 0.0.0.0:443 ssl crt /etc/haproxy/certs
   bind [::]:443 ssl crt /etc/haproxy/certs
```

instead of one
```
        bind [::]:443 v4v6 ssl crt /etc/haproxy/certs
```

will cause it will not sending ffff::, but actuall IPv4 address.. That I did not knew too. So if someone will looks for it, maybe it will find it here too
