### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by etemiz** [hoytech/strfry#5]
After running 'stream's for hours I tried to do an export:

$ ./strfry export | wc

strfry error: couldn't find leaf node in quadrable, corrupted DB?
2023-01-11 15:40:33.138 (   0.064s) [main thread     ]INFO| atexit

   3391   22061 1768370

**Comment by hoytech** [comment]
I *think* this is due to the bug you uncovered in #4 -- I'm doing some tests to try to reproduce this now.

**Comment by hoytech** [comment]
Yes I was able to reproduce it. The fix for #4 should prevent this from happening in the future.

I think this means that a relay was sending you duplicate events in the same stream.

It is possible to recover your database, but probably it's easiest just to `rm strfry-db/*.mdb` and start over, if the events aren't critical!
