### ISSUE TITLE
nip-11 pubkey as bech32 should be rejected or warned or well documented to avoid

### ISSUE THREAD

**Issue by mikedilger** [hoytech/strfry#52]
On too many relays, people are putting npub keys into the 'pubkey' field of nip-11, such as wss://relay.mostr.pub/, wss://relay.current.fyi/, wss://nostr.fmt.wiz.biz/, wss://nostr.mom/ (some of those are nostream, I'll file a separate bug for that).

NIP-11 states:
````
An administrative contact may be listed with a pubkey, in the same format as Nostr events (32-byte hex for a secp256k1 public key)
````

Could you (1) validate this and error or warn, or (2) make the comments/documentation very clear on this point so people don't make this mistake?

The gossip client is using strict typing and fails to deserialize these NIP-11 JSON objects, meaning the client is not providing any interesting relay information to the user, and gossip is presuming these clients do not support NIP-11 and not utilizing them fully.

Of course I could accept npub, but I fall into the camp of people who believe we should hold the line and defend the standards lest they proliferate into too many defacto variants.

**Comment by hoytech** [comment]
Good idea! I agree we should either make the spec say npubs are allowed, or encourage people to use the hex version.

I'm planning on doing 2 things for this:

* Make it so the default is an empty string, instead of `"unset"` placeholder. If it's an empty string I won't return the field at all in the NIP-11 response. This is NIP-11 compliant since it says "Any field may be omitted".
* Log a warning if pubkey contains anything other than 64 hex digits. On a misconfiguration, I don't really want to prevent the relay from starting or anything like that, so I think warning is the best middle ground here.

**Comment by hoytech** [comment]
I just pushed a commit to master that logs the following line on start or config file change:

    2023-07-20 18:02:40.252 (   0.036s) [main thread     ]WARN| Your relay.info.pubkey is incorrectly formatted. It should be 64 hex digits.
