### ISSUE TITLE
Work to change database

### ISSUE THREAD

**Issue by frbitten** [hoytech/strfry#66]
I haven't analyzed the code in depth yet.  But if you want to change the database, is the database isolated which allows for a simpler change?  Or is the code tightly integrated and would need to rewrite a lot to get it?  

For what I intend to do, using MongoDB would be ideal

**Comment by hoytech** [comment]
This would be a very substantial change, and is unlikely to ever happen. It would probably be easier to write a new relay from scratch.

strfry depends greatly on having extremely low latency access to the DB because it implements its own query engine. For an external DB you'd have to rewrite it to compose more complicated queries. It would probably be easier to start from a relay that uses SQL, such as [nostream](https://github.com/Cameri/nostream) or [nostr_rs_relay](https://sr.ht/~gheartsfield/nostr-rs-relay/).

**Comment by frbitten** [comment]
I first chose strfry because C++ is my main language and I found the project very well organized.

But thanks for the feedback. Saved me a few hours of code analysis. I will look for other options. I really didn't want to start a relay from scratch.
